"""
Django settings for solopi_tools project.

Generated by 'django-admin startproject' using Django 2.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=%em)2n^^vcqrox6j1s=1$y1nxl+l!bnu7h7g+jz-c4g3s^=(('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'loadtest',  # solopi性能测试
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'solopi_tools.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'solopi_tools.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
# 静态文件目录
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

# 上传文件的路径
MEDIA_URL = '/media/'
# 上传文件的目录
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# soloπCSV标题中文
CSV_TITLE_CN = {
    '累计全局上行流量': 'global_uplink',
    '累计全局下行流量': 'global_downlink',
    '累计应用上行流量': 'app_uplink',
    '累计应用下行流量': 'app_downlink',
    '平均电流': 'average_battery',
    '全局上行速率': 'global_uplink_speed',
    '全局下行速率': 'global_downlink_speed',
    '全局占用_CPU': 'CPU',
    '全局占用_Memory': 'memory',
    '实时电流': 'Real_time_battery',
    '刷新耗时': 'refresh_time_consuming',
    '响应耗时': 'response_time_consuming',
    '延迟次数': 'Delay_times',
    '延迟占比': 'Delay_ratio',
    '应用进程-appbrand0-3030': 'Application_process',
    '应用上行速率': 'app_uplink_speed',
    '应用下行速率': 'app_downlink_speed',
    '帧率': 'FPS',
    '最长延迟时间': 'Maximum_delay_time',
    'PrivateDirty内存-appbrand0-3030': 'PrivateDirty',
    'PSS内存-appbrand0-3030': 'PSS'}

# soloπCSV标题英文
CSV_TITLE_EN = {
    'global_uplink': '累计全局上行流量(KB)',
    'global_downlink': '累计全局下行流量(KB)',
    'app_uplink': '累计应用上行流量(KB)',
    'app_downlink': '累计应用下行流量(KB)',
    'average_battery': '平均电流(mA)',
    'global_uplink_speed': '全局上行速率(KB)',
    'global_downlink_speed': '全局下行速率(KB)',
    'CPU': '全局占用(%)',
    'memory': '全局占用(MB)',
    'Real_time_battery': '实时电流(mA)',
    'refresh_time_consuming': '刷新耗时(ms)',
    'response_time_consuming': '响应耗时(ms)',
    'Delay_times': '延迟次数(次)',
    'Delay_ratio': '延迟占比(%)',
    'Application_process': '应用进程-appbrand0-3030(%)',
    'app_uplink_speed': '应用上行速率(KB)',
    'app_downlink_speed': '应用下行速率(KB)',
    'FPS': '帧率(帧)',
    'Maximum_delay_time': '最长延迟时间(ms)',
    'PrivateDirty': 'PrivateDirty内存-appbrand0-3030(MB)',
    'PSS': 'PSS内存-appbrand0-3030(MB)'
}
